version: '3.9'

services:
  customers-postgres-init:
    image: postgres:14.16-alpine3.20
    container_name: customers-postgres-init
    env_file:
      - ../configs/local.env
    depends_on:
      - go-highload-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_CUSTOMERS}
    restart: no
    entrypoint: ["/init.sh"]
    volumes:
      - ./postgres-init.sh:/init.sh