version: '3.9'

services:
  inventory-cassandra-init:
    image: cassandra:4.0.17-jammy
    container_name: inventory-cassandra-init
    depends_on:
      - go-highload-cassandra
    environment:
      CASSANDRA_USER: ${CASSANDRA_USER}
      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
      CASSANDRA_KEYSPACE: ${CASSANDRA_KEYSPACE_INVENTORY}
    restart: no
    entrypoint: [ "/init.sh" ]
    volumes:
      - ./cassandra-init.sh:/init.sh