version: '3'

tasks:
  start:
    cmds:
      - colima start --vm-type=vz --cpu 4 --memory 4
  
  prune:
    cmds:
      - docker ps -q | xargs -r docker stop
      - docker system prune -af
      - docker volume prune -af
  
  clear:
    cmds:
      - docker ps -q | xargs -r docker stop
      - docker container prune -f
      - docker volume prune -af
      - docker network prune -f

  up:
    cmds:
      - docker compose -f ./deployments/docker-compose.yml --env-file ./configs/local.env up -d

  run:
    cmds:
      - docker run --rm -it {{.CLI_ARGS}} sh
